name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy to Vercel
        run: |
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "Deploying with team/org scope..."
            npx vercel --prod \
              --token=${{ secrets.VERCEL_TOKEN }} \
              --scope ${{ secrets.VERCEL_ORG_ID }} \
              --confirm \
              --project ${{ secrets.VERCEL_PROJECT_ID }}
          else
            echo "Deploying without scope (personal account)..."
            npx vercel --prod \
              --token=${{ secrets.VERCEL_TOKEN }} \
              --confirm \
              --project ${{ secrets.VERCEL_PROJECT_ID }}
          fi
